# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ebc297ec4acad85473c9ff4ea77df1b2649cb90f564f5fa6108dd6d33355867a8a0233e0833124b8c782ebb77f50b1e1f71aec10108682521c94cd156af0885

test:
  secret_key_base: 19a3c9bad971723cb94776faa776b0c974413b10a7f4d7befc9cc89f17ff6206cc2c33409f1832fccce46288e8d0633c2991721c58efd22a5d515d0c6a3d1134

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
